//! The command model.
//!
//! [`CommandSpec`] is the declarative half, generated by the
//! `#[derive(CommandSpec)]` macro: parsing, the Telegram menu, and `/help`
//! text. [`Command`] is the behavior half, implemented by the bot: the bot's
//! context type and a single `reply` entry point. Splitting them keeps the
//! bot's view free of teloxide while botkit owns the parsing machinery.

use anyhow::Result;

use crate::{reply::Reply, request::Request};

/// A single entry in the Telegram command menu.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MenuEntry {
    /// The command as Telegram shows it, prefix included (e.g. `/price`).
    pub command: String,
    /// Human-readable description shown in the menu.
    pub description: String,
}

/// Derive-generated command metadata.
///
/// `#[derive(botkit::CommandSpec)]` on a command enum produces parsing,
/// the command menu, and this trait's `help` text. Everything here is
/// teloxide-free.
pub trait CommandSpec: Sized {
    /// Human-readable command list (as `/help` shows it).
    fn help() -> String;

    /// The Telegram command menu.
    fn menu() -> Vec<MenuEntry>;

    /// Parse a message text into a command, or `None` if it is not one of
    /// ours. `bot_name` disambiguates `@botname` mentions in groups.
    fn parse(text: &str, bot_name: &str) -> Option<Self>;

    /// The bare command name of this variant (e.g. `"price"`).
    fn name(&self) -> &'static str;
}

/// The behavior a bot implements: its context plus one reply method.
#[crate::async_trait]
pub trait Command: CommandSpec + Clone + Send + Sync + 'static {
    /// Everything the commands need to produce their replies.
    type Ctx: Clone + Send + Sync + 'static;

    /// Produce the reply for this command.
    ///
    /// Errors are authored with `anyhow` in the command layer; botkit
    /// transports and renders them (`⚠️ {e:#}`).
    async fn reply(&self, ctx: &Self::Ctx, req: &Request) -> Result<Reply>;
}
