[package]
name = "degen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
botkit.workspace = true
coinmarketcap.workspace = true
coingecko.workspace = true
config.workspace = true
dotenvy.workspace = true
serde.workspace = true
telebots-core.workspace = true
tokio.workspace = true
