//! BotKit — a small framework for Telegram bots built on teloxide's long
//! polling.
//!
//! Botkit owns the transport (the poller, command parsing, `/help` text, the
//! Telegram menu, metrics, health, and graceful shutdown) so a bot only
//! describes **what its commands do**. Teloxide never appears in bot code.
//!
//! # What a bot writes
//!
//! A bot is two things: a command enum (the *spec*) and a [`Command`]
//! implementation (the *behavior*).
//!
//! The spec is a plain enum; `#[derive(CommandSpec)]` turns it into a
//! parser, the `/help` text, and the Telegram menu:
//!
//! ```ignore
//! #[derive(botkit::CommandSpec, Clone)]
//! #[command(rename_rule = "snake_case", description = "Echo commands:")]
//! enum Cmd {
//!     #[command(description = "Echo text back")]
//!     Echo(String),
//! }
//! ```
//!
//! The behavior is a single `reply` method that returns an explicit outcome:
//!
//! ```ignore
//! #[botkit::async_trait]
//! impl botkit::Command for Cmd {
//!     type Ctx = Ctx;
//!
//!     async fn reply(&self, _ctx: &Ctx, req: &botkit::Request)
//!         -> anyhow::Result<botkit::Reply>
//!     {
//!         let Cmd::Echo(text) = self else { unreachable!() };
//!         let mut block = telebots_core::Block::new();
//!         block.line(format!("You said: {text}"));
//!         Ok(botkit::Reply::text(block))
//!     }
//! }
//! ```
//!
//! Then `main` assembles the handlers into a [`Router`] and runs it:
//!
//! ```ignore
//! let router = botkit::Router::new(ctx).command::<Cmd>();
//!
//! botkit::Bot::builder()
//!     .token(token)
//!     .metrics_port(9101)
//!     .run(router)
//!     .await?;
//! ```
//!
//! # Beyond commands
//!
//! A [`Router`] composes multiple update kinds, all sharing one context:
//!
//! - `.command::<Cmd>()` — `/command` messages (the command enum).
//! - `.guarded_command::<Cmd, G>(guard)` — commands, after running a
//!   [`Guard`] that may short-circuit (rate limits, permissions, ...).
//! - `.inline_query(handler)` — `@botname <query>` inline queries, answered
//!   by an [`InlineHandler`] returning [`InlineAnswer`].
//! - `.callback(handler)` — inline-keyboard button taps, handled by a
//!   [`CallbackHandler`] that can edit the message or send a new one.
//! - `.message(handler)` — free-form text messages not consumed by a
//!   command branch, handled by a [`MessageHandler`].
//! - `.stats()` — the built-in `/stats` admin command (the bot's own
//!   metrics).
//!
//! # Concepts
//!
//! - [`CommandSpec`] — the derived, teloxide-free spec: parsing, the menu,
//!   and `/help` text. Generated by the `#[derive(CommandSpec)]` macro from
//!   the [`botkit-derive`] crate.
//! - [`Command`] — the behavior: the bot's context type and one `reply`
//!   method. Commands never call `send_message`.
//! - [`Reply`] — the explicit outcome a command produces: a text block, a
//!   photo, an in-place edit, or a supervised background [`Job`]. Text and
//!   photo replies can carry an inline [`Markup`] of [`Button`]s.
//! - [`Request`] — the teloxide-free slice of the update a command sees
//!   (chat, user, and reply context).
//! - [`Guard`] — a pre-command check that can short-circuit with a reply.
//! - [`CallbackHandler`] — the behavior for inline-keyboard button taps.
//! - [`Router`] — the set of update handlers a bot serves.
//! - [`Bot`] — the runner: poller, dispatcher, metrics server, heartbeat,
//!   and shutdown drain, wired from the router.
//! - [`Secret`] — a config value that never leaks into `Debug` output.
//!
//! # Rendering
//!
//! Bots build text as [`telebots_core::Block`]s (a dependency of every bot)
//! and return them inside [`Reply`]. Data types and botkit never know how a
//! block is presented — rendering is consumer-side.
//!
//! # Errors
//!
//! [`Command::reply`] returns [`anyhow::Result`]; botkit transports and
//! renders those errors uniformly (`⚠️ {e:#}`) because the command layer
//! authors them. botkit's own startup failures are the typed [`Error`].

mod bot;
mod branches;
mod builtin;
mod config;
mod dispatch;
mod error;
mod guard;
mod handlers;
mod health;
mod markup;
mod messenger;
mod metrics;
mod reply;
mod request;
mod router;
mod supervisor;
mod telemetry;

pub use async_trait::async_trait;
pub use bot::{Bot, BotBuilder};
pub use botkit_derive::CommandSpec;
pub use config::Secret;
pub use error::Error;
pub use guard::{Guard, NoGuard};
pub use handlers::{
    CallbackHandler, Command, CommandSpec, InlineAnswer, InlineHandler, InlineResult, MenuEntry,
    MessageHandler,
};
pub use markup::{Button, Markup};
pub use metrics::UsageReporter;
pub use reply::{BoxFuture, Job, JobCtx, Reply};
pub use request::{CallbackRequest, ChatKind, InlineRequest, MessageRequest, Request};
pub use router::Router;
pub use telemetry::Telemetry;
