//! BotKit — a small framework for Telegram bots built on teloxide's long
//! polling.
//!
//! Botkit owns the transport (the poller, command parsing, `/help` text, the
//! Telegram menu, metrics, health, and graceful shutdown) so a bot only
//! describes **what its commands do**. Teloxide never appears in bot code.
//!
//! # What a bot writes
//!
//! A bot is two things: a command enum (the *spec*) and a [`Command`]
//! implementation (the *behavior*).
//!
//! The spec is a plain enum; `#[derive(CommandSpec)]` turns it into a
//! parser, the `/help` text, and the Telegram menu:
//!
//! ```ignore
//! #[derive(botkit::CommandSpec, Clone)]
//! #[command(rename_rule = "snake_case", description = "Echo commands:")]
//! enum Cmd {
//!     #[command(description = "Echo text back")]
//!     Echo(String),
//! }
//! ```
//!
//! The behavior is a single `reply` method that returns an explicit outcome:
//!
//! ```ignore
//! #[botkit::async_trait]
//! impl botkit::Command for Cmd {
//!     type Ctx = Ctx;
//!
//!     async fn reply(&self, _ctx: &Ctx, req: &botkit::Request)
//!         -> anyhow::Result<botkit::Reply>
//!     {
//!         let Cmd::Echo(text) = self else {
//!             unreachable!();
//!         };
//!         let mut block = telebots_core::Block::new();
//!         block.line(format!("You said: {text}"));
//!         Ok(botkit::Reply::Text(block))
//!     }
//! }
//! ```
//!
//! Then `main` builds and runs it:
//!
//! ```ignore
//! botkit::Bot::builder()
//!     .token(token)
//!     .metrics_port(9101)
//!     .run::<Cmd>(ctx)
//!     .await?;
//! ```
//!
//! # Concepts
//!
//! - [`CommandSpec`] — the derived, teloxide-free spec: parsing, the menu,
//!   and `/help` text. Generated by the `#[derive(CommandSpec)]` macro from
//!   the [`botkit-derive`] crate.
//! - [`Command`] — the behavior: the bot's context type and one `reply`
//!   method. Commands never call `send_message`.
//! - [`Reply`] — the explicit outcome a command produces: a text block, a
//!   photo, an in-place edit, or a supervised background [`Job`].
//! - [`Request`] — the teloxide-free slice of the update a command sees
//!   (chat, user, and reply context).
//! - [`Bot`] — the runner: poller, dispatcher, metrics server, heartbeat,
//!   and shutdown drain, wired from the command enum.
//! - [`Secret`] — a config value that never leaks into `Debug` output.
//!
//! # Rendering
//!
//! Bots build text as [`telebots_core::Block`]s (a dependency of every bot)
//! and return them inside [`Reply`]. Data types and botkit never know how a
//! block is presented — rendering is consumer-side.
//!
//! # Errors
//!
//! [`Command::reply`] returns [`anyhow::Result`]; botkit transports and
//! renders those errors uniformly (`⚠️ {e:#}`) because the command layer
//! authors them. botkit's own startup failures are the typed [`Error`].

mod bot;
pub mod command;
pub mod config;
pub mod error;
mod health;
mod metrics;
mod reply;
pub mod request;
pub mod telemetry;

pub use async_trait::async_trait;
pub use bot::{Bot, BotBuilder};
pub use botkit_derive::CommandSpec;
pub use command::{Command, CommandSpec, MenuEntry};
pub use config::Secret;
pub use error::Error;
pub use reply::{BoxFuture, Job, JobCtx, Reply};
pub use request::{ChatKind, Request};
pub use telemetry::Telemetry;
