[package]
name = "imagine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
botkit.workspace = true
cloudflare-ai.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
storage.workspace = true
telebots-core.workspace = true
teloxide.workspace = true
tokio.workspace = true
tracing.workspace = true
